copyright: Copyright &copy; 2016-2020
site_name: "[Boost::ext].SML"
site_url: http://boost-ext.github.io/sml
site_author: Kris Jusiak
repo_url: https://github.com/boost-ext/sml
repo_name: sml
docs_dir: doc
use_directory_urls: false
theme:
  name: null
  custom_dir: !!python/object/apply:os.getenv ["MKDOCS_THEME_DIR"]
google_analytics: ['UA-73083568-1', 'auto']
extra_javascript: []
extra_css: []

nav:
- Introduction: index.md
- Overview: overview.md
- Features/Benchmarks: benchmarks.md
- Tutorial/Workshop: tutorial.md
- UML vs SML: uml_vs_sml.md
- User Guide: user_guide.md
- Examples: examples.md
- FAQ: faq.md
- CHANGELOG: CHANGELOG.md
